// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

export enum ResponseResultType {
  RESPONSE_RESULT_UNSPECIFIED = 0,
  RESPONSE_RESULT_NOOP = 1,
  RESPONSE_RESULT_SUCCESS = 2,
}
