// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgClearAdminResponse {
  static encode(message: MsgClearAdminResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgClearAdminResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgClearAdminResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgClearAdminResponse(
  message: MsgClearAdminResponse
): Uint8Array {
  return Protobuf.encode(message, MsgClearAdminResponse.encode);
}

export function decodeMsgClearAdminResponse(
  buffer: Uint8Array
): MsgClearAdminResponse {
  return Protobuf.decode<MsgClearAdminResponse>(
    buffer,
    MsgClearAdminResponse.decode
  );
}
