// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class MsgIBCCloseChannel {
  static encode(message: MsgIBCCloseChannel, writer: Writer): void {
    writer.uint32(18);
    writer.string(message.channel);
  }

  static decode(reader: Reader, length: i32): MsgIBCCloseChannel {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgIBCCloseChannel();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          message.channel = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  channel: string;

  constructor(channel: string = "") {
    this.channel = channel;
  }
}

export function encodeMsgIBCCloseChannel(
  message: MsgIBCCloseChannel
): Uint8Array {
  return Protobuf.encode(message, MsgIBCCloseChannel.encode);
}

export function decodeMsgIBCCloseChannel(
  buffer: Uint8Array
): MsgIBCCloseChannel {
  return Protobuf.decode<MsgIBCCloseChannel>(buffer, MsgIBCCloseChannel.decode);
}
