// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgUpdateAdminResponse {
  static encode(message: MsgUpdateAdminResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgUpdateAdminResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgUpdateAdminResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgUpdateAdminResponse(
  message: MsgUpdateAdminResponse
): Uint8Array {
  return Protobuf.encode(message, MsgUpdateAdminResponse.encode);
}

export function decodeMsgUpdateAdminResponse(
  buffer: Uint8Array
): MsgUpdateAdminResponse {
  return Protobuf.decode<MsgUpdateAdminResponse>(
    buffer,
    MsgUpdateAdminResponse.decode
  );
}
